services:
  minio:
    image: docker.io/bitnami/minio:2022.5.26
    restart: always
    ports:
      - '9900:9000'
      - '9910:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - 's3_newspaper:/data:rw'

volumes:
  s3_newspaper:
